//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASK_BD1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Vote
    {
        public int ques_id { get; set; }
        public int ans_id { get; set; }
        public string email { get; set; }
        public int up_down { get; set; }

        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
